<template>
	<div>
		<div class="row form-inline">
			<div class="form-floating w-100">
				<input  v-bind:value="calculator_input" v-on:change="alert('Not implemented');" id="calculator_input" type="text" class="form-control rounded-0 rounded-top" style="text-align: right; font-size: 16pt;"> <!-- readonly -->
				<label for="calculator_input" class="text-dark h4">
					Result
				</label>
			</div>
		</div>

		<div class="h3">
			<div class="row p-0 m-0">
				<button class="w-50 btn-warning button5" @click="clean()">C</button>
				<button class="w-50 button5" @click="back()">&larr;</button>
			</div>
			<div class="row p-0 m-0" role="toolbar" aria-label="Toolbar with button groups" id="calculator-bits"> <!-- may be generated by js -->
				
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit31" value="0">31</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit30" value="0">30</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit29" value="0">29</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit28" value="0">28</button>
					</div>
				</div>
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit27" value="0">27</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit26" value="0">26</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit25" value="0">25</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit24" value="0">24</button>
					</div>
				</div>
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit23" value="0">23</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit22" value="0">22</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit21" value="0">21</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit20" value="0">20</button>
					</div>
				</div>
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit19" value="0">19</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit18" value="0">18</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit17" value="0">17</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit16" value="0">16</button>
					</div>
				</div>
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit15" value="0">15</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit14" value="0">14</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit13" value="0">13</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit12" value="0">12</button>
					</div>
				</div>
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit11" value="0">11</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit10" value="0">10</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit9" value="0">9</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit8" value="0">8</button>
					</div>
				</div>
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit7" value="0">7</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit6" value="0">6</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit5" value="0">5</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit4" value="0">4</button>
					</div>
				</div>
				<div class="w-50 align-items-center m-0 p-0">
					<div class="w-100 btn-group center-block">
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit3" value="0">3</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit2" value="0">2</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit1" value="0">1</button>
						<button @click="bitfield_inverse($event.target)" class="btn btn-dark calculator-bit border border-dark button5" id="calculator-bit0" value="0">0</button>
					</div>
				</div>
			</div>
			<!--  <script type="text/javascript" src="/js/calculator.js"></script> -->
			
			<div class="row p-0 m-0">
				<button class="w-25 button5" @click="insert('+')">+</button>
				<button class="w-25 button5" @click="insert('-')">-</button>
				<button class="w-25 button5" @click="insert('*')">&times;</button>
				<button class="w-25 button5" @click="insert('/')">&divide;</button>
			</div>
			<div class="row p-0 m-0">
				<button class="w-25 button5" @click="insert('7')">7</button>
				<button class="w-25 button5" @click="insert('8')">8</button>
				<button class="w-25 button5" @click="insert('9')">9</button>
				<button class="w-25 button5" @click="insert('(')">(</button>
			</div>
			<div class="row p-0 m-0">
				<button class="w-25 button5" @click="insert('4')">4</button>
				<button class="w-25 button5" @click="insert('5')">5</button>
				<button class="w-25 button5" @click="insert('6')">6</button>
				<button class="w-25 button5" @click="insert(')')">)</button>
			</div>
			<div class="row p-0 m-0">
				<button class="w-25 button5" @click="insert('1')">1</button>
				<button class="w-25 button5" @click="insert('2')">2</button>
				<button class="w-25 button5" @click="insert('3')">3</button>
				<button class="w-25 btn-primary button5" @click="equal()">=</button>
			</div>
			<div class="row p-0 m-0">
				<button class="w-50 button5" @click="insert('0')">0</button>
				<button class="w-50 button5" @click="insert('.')">.</button>
			</div>
		</div>
	</div>
</template>

<script>
	export default {
		name: 'calculator',
		//template: "<div>NAME {{ name }}</div>",
		// props: {
		// 	email: String,
		// 	password: String,
		// 	remember_me:Boolean,
		// },
		data() {
			var bitwidget_values = new Array();
			for(var b = 0; b < 32 ; b++) {
				bitwidget_values.unshift({ value: 0 })
				//document.getElementById("calculator-bit" + b)
			}
			//console.log(bitwidget_values)
			return {
				bitwidget_values: bitwidget_values,
				bitwidget_state: false,
				calculator_input: "",
				calculator_input_prev: "",
			}
		},
		methods: {
			bitfield_update(argument) {
				//console.log(argument)
				// console.log(argument.textContent)
				//this.bitwidget_values[argument.textContent] ^= 1
				// argument.value ^= 1
				if(argument.value != "0") {
					argument.setAttribute("class", "btn btn-primary calculator-bit border border-dark button5"); // btn-dark
				} else {
					argument.setAttribute("class", "btn btn-dark calculator-bit border border-dark button5"); // btn-danger
				}
				// create_bit_buttons()
				//console.log(argument.value, argument.textContent);
			},
			bitfield_inverse(argument) {

				//console.log("bitfield_inverse", argument.textContent, argument.value, typeof(argument.value));
				//this.bitwidget_values[argument.textContent] ^= 1
				// argument.value ^= 1

				//argument.value = !argument.value;
				if(argument.value != 0) {
					//argument.value = false;
					//console.log("argument.value = false;");
					argument.value = 0;
				} else {
					//argument.value = true;
					//console.log("argument.value = true;");
					argument.value = 1;
				}

				this.bitwidget_values[argument.textContent].value = parseInt(argument.value);

				//console.log(this.bitwidget_values)
				//console.log("bitfield_inverse", argument.textContent, argument.value, typeof(argument.value));
				this.bitfield_update(argument);
				//console.log("bitfield_inverse", argument.textContent)
				let value = 0;
				
				// this.items = 7
				//console.log(this.items)

				this.bitwidget_values.forEach(function(item, index, array) {
					value += (2 ** index ) * item.value;
				});
				// console.log(value)
				if(value != 0) {
					if(this.bitwidget_state) {
						this.calculator_input = this.calculator_input_prev;
					}
					this.insert(value, true);
				} else {
					this.calculator_input = this.calculator_input_prev;
				}

				//console.log(value);
				var tmp = [];
				this.bitwidget_values.forEach(function(item, index, array) { tmp.push(item.value);});
				//console.log(tmp);
			},
			bitfieldwidget_clear(selfo) {
				selfo.bitwidget_values.forEach(function(item, index, array) {
					//console.log(item.textContent)
					//item.value = 0;
					selfo.bitwidget_values[index].value = 0;
					var q = document.getElementById("calculator-bit" + index);
					q.value = 0;
					// selfo.bitfield_update(item);
					selfo.bitfield_update(q);
				});
			},
			insert(num, bitwidget_state_l=false) {
				this.bitwidget_state = bitwidget_state_l;
				if(this.bitwidget_state === false) {
					this.bitfieldwidget_clear(this);
				}

				this.calculator_input_prev = this.calculator_input;
				this.calculator_input = this.calculator_input + num;
			},
			clean() {
				this.bitwidget_state = false;
				this.bitfieldwidget_clear(this);
				this.calculator_input_prev = this.calculator_input;
				this.calculator_input = "";
			},
			back() {
				// console.log("this", this)
				this.bitwidget_state = false;
				this.bitfieldwidget_clear(this);
				var exp = this.calculator_input;
				this.calculator_input_prev = this.calculator_input;
				this.calculator_input = exp.substring(0, exp.length-1);
			},
			equal() {
				this.bitwidget_state = false;
				this.bitfieldwidget_clear(this);
				var exp = this.calculator_input;
				this.calculator_input_prev = this.calculator_input;
				if(exp) {
					this.calculator_input = eval(exp);
				}
			},
		},
		mounted() {
			
		},
	}
</script>

<style>
	
</style>
